### ISSUE TITLE
Place-Block flag also prevents using items on blocks

### ISSUE THREAD

**Issue by Z3R0TR0N** [Z0rdak/Yet-Another-World-Protector#109] opened 2024-05-12 03:34 UTC
Hi,

We've had complaints that adding the "place-block" flag to a region also prevents players from using items on blocks, which is a different flag entirely. I've confirmed this by being unable to place a written book back into its lectern. The region in question has the following flags:
- break-blocks 
- place-blocks 
- explosion-blocks 
- explosion-entities
- spawn-portal 
- spawning-monster 
I've attached a screenshot to confirm:
<img width="844" alt="Screenshot 2024-05-11 at 11 29 48 PM" src="https://github.com/Z0rdak/Yet-Another-World-Protector/assets/109635033/5a9d44dc-a9d7-4d93-81d4-ad897b36558f">

However, we'd like players to be able to place books back into lecterns (they can remove books, but not replace them), and to add dyes & glow ink to signs (for our mailboxes). 
We've also had complaints that trying to open containers (i.e., barrels) while holding a tool or item (e.g., a sword) in the player's main hand also doesn't work. The place-block flag alert likewise appears and denies this action.

My understanding is this should only be prevented by the use-items flag, which is not present, nor is it present in any parent / dimensional regions. Is place-blocks meant to prevent using items on blocks, or is this a bug?

We use Fabric 0.15.10 for Minecraft 1.20.4, with YAWP 0.0.2.9-Beta3-Fabric.

**Comment by Z0rdak** [comment] 2024-05-12 08:24
> We've had complaints that adding the "place-block" flag to a region also prevents players from using items on blocks, which is a different flag entirely.

This should not happen at all. Its not the intended behaviour.

At first this sounds like an issue with the vanilla server spawn protection. Since the region is named spawn its possible that the region is at the same location as the vanilla spawn protection.

Please try to disable the vanilla spawn protection first and check it again and report back. If the issue still exists, I am more than happy to take a look into it.

Best regards

**Comment by Z0rdak** [comment] 2024-05-12 20:37
So I've investigated this issue. It's a "bug". It should not be that way and affects any fabric version. 

I'll see how to fix it in the next days and publish a fix.

**Comment by Z3R0TR0N** [comment] 2024-07-04 04:28
Hi, 

Just wanted to provide an update to your suggested fix. You were correct— the vanilla spawn protections were interfering with YAWP, so turning off the YAWP protection and sticking to vanilla protections worked fine. Thank you!
Best of luck resolving this bug, however!

**Comment by Z0rdak** [comment] 2024-07-04 04:51
Thanks for the update.
I’ll let you know when it is fixed by closing this issue. 
best regards

**Comment by Z0rdak** [comment] 2024-09-14 19:59
I pretty sure I solved this issue in my current dev build. 
If nothing creeps up, I will release a updated version someday next week.

**Closed as completed** 2024-09-20 07:31 UTC
Labels: bug, investigation
